//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Online_Examination_System
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class User
    {
        public int UserId { get; set; }
        [Required(ErrorMessage = "Please Enter Username", AllowEmptyStrings = false)]
        public string UserName { get; set; }
        [Required(ErrorMessage = "Please Enter Username", AllowEmptyStrings = false)]
      
        public string Password { get; set; }
        [DataType(DataType.EmailAddress)]
        public string EmailId { get; set; }
        public string UserType { get; set; }
        [DataType(DataType.PhoneNumber)]
        public string PhoneNo { get; set; }
        public string Organization { get; set; }
 
        public string ConfirmPassword { get; set; }
    }
}
